<?php

namespace Database\Seeders;

use App\Models\Student;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user_students = [
            [
                'username' => 'D0220375',
                'email' => 'ahmadsurya@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('ahmadsurya@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220376',
                'email' => 'budisantoso@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('budisantoso@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220377',
                'email' => 'cindywijaya@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('cindywijaya@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220378',
                'email' => 'dianpratiwi@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('dianpratiwi@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220379',
                'email' => 'ekaputra@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('ekaputra@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220380',
                'email' => 'faisalrahman@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('faisalrahman@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220381',
                'email' => 'gitadamayanti@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('gitadamayanti@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220382',
                'email' => 'hanisusanti@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('hanisusanti@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220383',
                'email' => 'indragunawan@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('indragunawan@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'username' => 'D0220384',
                'email' => 'jokosetiawan@unsulbar.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s', time()),
                'password' => \bcrypt('jokosetiawan@unsulbar.ac.id'),
                'role_id' => 4,
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],

        ];
        
        foreach($user_students as $key => $student) {
            User::create($student);
        }

        $students = [
            [
                'user_id' => 9,
                'nim_mhs' => 'D0220375',
                'nama_mhs' => 'Ahmad Surya',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'Sistem Cerdas',
                'about' => 'Ok',
                'phone_number' => '081234567890',
                'instagram_profile' => 'ahmadsurya',
                'linkedin_profile' => 'ahmadsurya',
                'github_profile' => 'ahmadsurya',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 10,
                'nim_mhs' => 'D0220376',
                'nama_mhs' => 'Budi Santoso',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'Sistem Cerdas',
                'about' => 'Ok',
                'phone_number' => '081234567893',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 11,
                'nim_mhs' => 'D0220377',
                'nama_mhs' => 'Cindy Wijaya',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'Sistem Cerdas',
                'about' => 'Ok',
                'phone_number' => '082345678901',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 12,
                'nim_mhs' => 'D0220378',
                'nama_mhs' => 'Dian Pratiwi',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'RPL',
                'about' => 'Ok',
                'phone_number' => '083456789012',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 13,
                'nim_mhs' => 'D0220379',
                'nama_mhs' => 'Eka Putra',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'RPL',
                'about' => 'Ok',
                'phone_number' => '081234567891',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 14,
                'nim_mhs' => 'D0220380',
                'nama_mhs' => 'Faisal Rahman',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'RPL',
                'about' => 'Ok',
                'phone_number' => '082345678902',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 15,
                'nim_mhs' => 'D0220381',
                'nama_mhs' => 'Gita Damayanti',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'IOT',
                'about' => 'Ok',
                'phone_number' => '083456789013',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 16,
                'nim_mhs' => 'D0220382',
                'nama_mhs' => 'Hani Susanti',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'IOT',
                'about' => 'Ok',
                'phone_number' => '081234567892',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 17,
                'nim_mhs' => 'D0220383',
                'nama_mhs' => 'Indra Gunawan',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'IOT',
                'about' => 'Ok',
                'phone_number' => '082345678903',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
            [
                'user_id' => 18,
                'nim_mhs' => 'D0220384',
                'nama_mhs' => 'Joko Setiawan',
                'angkatan_mhs' => '2020',
                'prodi_mhs' => 'informatika',
                'status_mhs' => '1',
                'concentration' => 'IOT',
                'about' => 'Ok',
                'phone_number' => '083456789014',
                'instagram_profile' => '#',
                'linkedin_profile' => '#',
                'github_profile' => '#',
                'created_at' => date('Y-m-d H:i:s', time()),
                'updated_at' => date('Y-m-d H:i:s', time()),
            ],
        ];

        foreach($students as $key => $student) {
            Student::create($student);
        }
    }
}
